/* ============================================================
   axonometric.js — "Exploded axonometric" component (track-1).
   Index list (left) drives which slab is highlighted in the
   isometric drawing (right). All content lives in LAYERS below;
   all geometry is generated by axo-geometry.js from numbers.
   ============================================================ */
(function () {

  const LAYERS = [
    {
      id: '01', title: 'Plan', geometry: 'plan',
      subtitle: 'Richting en keuzes',
      line: 'Objectives, geprijsd als outcome en als target-maturity.',
    },
    {
      id: '02', title: 'Value streams', geometry: 'streams',
      subtitle: 'Waar effect meetbaar wordt',
      line: 'Van trigger tot geleverde waarde, per stakeholder. Meetpunt en scope.',
    },
    {
      id: '03', title: 'Capabilities', geometry: 'capabilities',
      subtitle: 'Wat er verandert',
      line: 'Gedeeld over streams, permanent geowned, met maturity-gap.',
    },
    {
      id: '04', title: 'Means', geometry: 'means',
      subtitle: 'Wie, hoeveel, in welk ritme',
      line: 'Teams, capaciteit, besturing. Twee assen: per objective en per hotspot.',
    },
  ];

  const AXO_SECTION_HTML = `
    <div class="wrap">
      <div class="axo-grid">
        <div class="section-label reveal">
          <p class="section-eyebrow">The stack</p>
          <h2>Plan to means,<br>in one motion</h2>
          <p class="sub" style="margin-top:16px;" data-i18n="stack-sub">Four layers, exploded so you can see how a decision at the top lands as capacity at the bottom — and where it's meant to come back around.</p>
          <div class="axo-index" role="group" aria-label="Architecture layers" id="axoIndex"></div>
        </div>
        <div class="axo-drawing reveal" id="axoDrawing"></div>
      </div>
    </div>
  `;

  const buildIndexHTML = () => LAYERS.map(l => `
    <button type="button" class="axo-row" id="axo-btn-${l.id}" data-id="${l.id}" aria-pressed="false" aria-describedby="axo-desc-${l.id}">
      <span class="axo-row-top"><span class="axo-num">${l.id}</span><span class="axo-title">${l.title}</span></span>
      <span class="axo-desc" id="axo-desc-${l.id}"><span class="axo-desc-inner">
        <span class="axo-subtitle">${l.subtitle}</span>
        <span class="axo-text">${l.line}</span>
      </span></span>
    </button>
  `).join('');

  /* ── Geometry: shared footprint, one baseY per slab ─────── */
  const W = 240, D = 160;                 // plate footprint (x, z)
  const BASE = { '04': 0, '03': 90, '02': 180, '01': 270 }; // elevation

  const buildSVG = () => {
    const G = window.AxoGeometry;
    let s = '';

    // 04 · Means — plate, team clusters, board, outcome loop
    const meansTop = BASE['04'] + 6;
    s += `<g data-layer="04">`;
    s += G.box(0, 0, BASE['04'], W, D, 6);
    [[50, 100], [120, 100], [190, 100]].forEach(([cx, cz]) => {
      [[0, 0], [9, 5], [-4, 8]].forEach(([dx, dz]) => {
        s += G.cylinder(cx + dx, cz + dz, meansTop, 6, 14);
      });
    });
    s += G.box(60, 20, meansTop, 120, 30, 8); // the board
    s += `</g>`;

    // 03 · Capabilities — 5×3 grid, 2 taller hotspots
    const capTop = BASE['03'] + 6;
    const cols = [24, 72, 120, 168, 216], rows = [40, 80, 120];
    const hotspots = new Set(['72,80', '168,80']);
    s += `<g data-layer="03">`;
    s += G.box(0, 0, BASE['03'], W, D, 6);
    rows.forEach(z => cols.forEach(x => {
      const h = hotspots.has(`${x},${z}`) ? 26 : 10;
      s += G.box(x - 7, z - 7, capTop, 14, 14, h);
    }));
    s += `</g>`;

    // Plan cubes drop guide-lines through the gap onto the two
    // hotspots — drawn before Value streams so its plate occludes
    // the middle stretch of the line, as if passing "through" it.
    s += `<g data-layer="01">`;
    s += G.line([72, BASE['01'] + 6 + 34, 80], [72, capTop + 26, 80]);
    s += G.line([168, BASE['01'] + 6 + 28, 80], [168, capTop + 26, 80]);
    s += `</g>`;

    // 02 · Value streams — 4 beams with end-caps, 1 highlighted
    const stTop = BASE['02'] + 6;
    const bars = [[24, 10], [72, 10], [120, 10], [168, 14]]; // last = highlighted
    s += `<g data-layer="02">`;
    s += G.box(0, 0, BASE['02'], W, D, 6);
    bars.forEach(([x, h]) => {
      s += G.box(x - 16, 20, stTop, 32, 120, h);
      s += G.box(x - 21, 10, stTop, 42, 10, h + 4); // end-cap
    });
    s += `</g>`;

    // Highlighted beam's own short line down to the shared hotspot
    s += `<g data-layer="02">${G.line([168, stTop + 14, 80], [168, capTop + 26, 80])}</g>`;

    // 01 · Plan — plate + 5 cubes of varying height
    const planTop = BASE['01'] + 6;
    s += `<g data-layer="01">`;
    s += G.box(0, 0, BASE['01'], W, D, 6);
    [[24, 18], [72, 34], [120, 22], [168, 28], [216, 16]].forEach(([x, h]) => {
      s += G.box(x - 9, 71, planTop, 18, 18, h);
    });
    s += `</g>`;

    // Outcome loop: returns from Means, up the left side, to Plan
    s += `<g data-layer="04">`;
    const loop = [[40, meansTop + 14, 100], [-30, meansTop + 14, 100], [-30, planTop, 100], [10, planTop, 80]];
    for (let i = 0; i < loop.length - 1; i++) s += G.line(loop[i], loop[i + 1]);
    s += G.arrow(loop[loop.length - 2], loop[loop.length - 1]);
    s += `</g>`;

    return `<svg class="axo-svg" viewBox="0 0 800 700" fill="none" role="img" aria-labelledby="axoTitle axoDesc">
      <title id="axoTitle">Exploded axonometric of the architecture stack</title>
      <desc id="axoDesc">Four stacked layers, top to bottom: Plan, Value streams, Capabilities, Means — connected by thin guide lines showing how objectives cascade into shared capabilities, and how delivery reports back as an outcome loop.</desc>
      <g transform="translate(360,400) scale(1.3)">${s}</g>
    </svg>`;
  };

  /* ── Wiring: hover/focus previews, click persists ───────── */
  const init = () => {
    const root = document.querySelector('[data-inject-axo]');
    if (!root) return;
    root.innerHTML = AXO_SECTION_HTML;

    const indexEl = root.querySelector('#axoIndex');
    const drawEl  = root.querySelector('#axoDrawing');
    indexEl.innerHTML = buildIndexHTML();
    drawEl.innerHTML  = buildSVG();

    const svgEl   = drawEl.querySelector('svg');
    const layerEls = svgEl.querySelectorAll('[data-layer]');
    const buttons = Array.from(indexEl.querySelectorAll('.axo-row'));
    let selected = null;

    const applyState = (activeId) => {
      buttons.forEach(b => b.classList.toggle('is-active', activeId !== null && b.dataset.id === activeId));
      layerEls.forEach(g => {
        g.style.opacity = activeId === null ? '' : (g.dataset.layer === activeId ? '1' : '.15');
      });
    };

    const setSelected = (id) => {
      selected = id;
      buttons.forEach(b => b.setAttribute('aria-pressed', String(b.dataset.id === id)));
      applyState(id);
    };

    buttons.forEach((b, i) => {
      b.addEventListener('mouseenter', () => applyState(b.dataset.id));
      b.addEventListener('focus',      () => applyState(b.dataset.id));
      b.addEventListener('mouseleave', () => applyState(selected));
      b.addEventListener('blur',       () => applyState(selected));
      b.addEventListener('click',      () => setSelected(b.dataset.id));
      b.addEventListener('keydown', (e) => {
        if (!['ArrowDown', 'ArrowRight', 'ArrowUp', 'ArrowLeft'].includes(e.key)) return;
        e.preventDefault();
        const dir = (e.key === 'ArrowDown' || e.key === 'ArrowRight') ? 1 : -1;
        buttons[(i + dir + buttons.length) % buttons.length].focus();
      });
    });
  };

  // Runs at top level (like main.js's own section injections) so the
  // .reveal elements below exist before main.js wires up its scroll
  // observer — this script tag must stay ordered before main.js's.
  init();
})();
